language: java

# skip installation step
install: true

script:
- mvn -f ciphers/pom.xml clean verify coveralls:report
- mvn -f ciphers/pom.xml clean verify sonar:sonar

sudo: false

cache:
  directories:
  - $HOME/.m2


